<P>	WORD	BEGINOFSENTENCE NEWPARAGRAPH 
In	WORD	
categorie	WORD	
I	WORD	
"	PUNCTUATION	NOSPACE BEGINQUOTE 
Landbouwuitgaven	WORD	NOSPACE 
,	PUNCTUATION	
marktsteun	WORD	NOSPACE 
"	PUNCTUATION	ENDQUOTE 
zitten	WORD	
wij	WORD	
al	WORD	
aan	WORD	
de	WORD	
grens	WORD	
van	WORD	
de	WORD	
marge	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Categorie	WORD	BEGINOFSENTENCE 
IV	WORD	
"	PUNCTUATION	NOSPACE BEGINQUOTE 
Extern	WORD	BEGINOFSENTENCE 
beleid	WORD	NOSPACE 
.	PUNCTUATION	
daar	WORD	
kom	WORD	
ik	WORD	
straks	WORD	
nog	WORD	
op	WORD	
teru	WORD	NOSPACE 
.	PUNCTUATION	
barst	WORD	
letterlijk	WORD	
uit	WORD	
haar	WORD	
voegen	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Bij	WORD	BEGINOFSENTENCE 
categorie	WORD	
V	WORD	
weten	WORD	
we	WORD	
enerzijds	WORD	
niet	WORD	
wat	WORD	
de	WORD	
administratieve	WORD	
hervorming	WORD	
van	WORD	
de	WORD	
Commissie	WORD	
gaat	WORD	
kosten	WORD	
en	WORD	
slaan	WORD	
wij	WORD	
anderzijds	WORD	
met	WORD	
grote	WORD	
ongerustheid	WORD	
het	WORD	
probleem	WORD	
van	WORD	
de	WORD	
pensioenen	WORD	
gade	WORD	NOSPACE 
,	PUNCTUATION	
waar	WORD	
geen	WORD	
gepaste	WORD	
uitgaven	WORD	
voor	WORD	
zijn	WORD	
opgenomen	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

In	WORD	BEGINOFSENTENCE 
categorie	WORD	
VII	WORD	
betreffende	WORD	
pretoetreding	WORD	
is	WORD	
er	WORD	
voor	WORD	
het	WORD	
streven	WORD	
naar	WORD	
een	WORD	
snellere	WORD	NOSPACE 
,	PUNCTUATION	
grotere	WORD	
uitbreidin	WORD	NOSPACE 
.	PUNCTUATION	
als	WORD	
ik	WORD	
het	WORD	
zo	WORD	
zeggen	WORD	
ma.	ABBREVIATION-KNOWN	
geen	WORD	
gepast	WORD	
kredietvolume	WORD	
uitgetrokken	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Landen	WORD	BEGINOFSENTENCE 
zoals	WORD	
Cyprus	WORD	
en	WORD	
Malta	WORD	
verkeren	WORD	
nu	WORD	
reeds	WORD	
in	WORD	
een	WORD	
onzekere	WORD	
situatie	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Heel	WORD	BEGINOFSENTENCE 
de	WORD	
begrotingsprogrammering	WORD	
stond	WORD	
dus	WORD	
in	WORD	
het	WORD	
teken	WORD	
van	WORD	
ongewisheid	WORD	NOSPACE 
,	PUNCTUATION	
maar	WORD	
legde	WORD	
tegelijkertijd	WORD	
het	WORD	
Europees	WORD	
Parlement	WORD	
aan	WORD	
banden	WORD	NOSPACE 
,	PUNCTUATION	
omdat	WORD	
wij	WORD	
voor	WORD	
het	WORD	
eerst	WORD	
moesten	WORD	
werken	WORD	
met	WORD	
minder	WORD	
flexibiliteit	WORD	
en	WORD	
minder	WORD	
geld	WORD	
en	WORD	
niet	WORD	
meer	WORD	
geld	WORD	NOSPACE 
,	PUNCTUATION	
hetgeen	WORD	
men	WORD	
als	WORD	
tegenprestatie	WORD	
had	WORD	
kunnen	WORD	
verwachten	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

De	WORD	BEGINOFSENTENCE 
situatie	WORD	
is	WORD	
dus	WORD	
paradoxaal	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

<P>	WORD	BEGINOFSENTENCE 
Dit	WORD	
verhaal	WORD	
wordt	WORD	
echter	WORD	
pas	WORD	
goed	WORD	
surrealistisch	WORD	
als	WORD	
wij	WORD	
kijken	WORD	
naar	WORD	
deze	WORD	
begrotingsprocedure	WORD	
voor	WORD	
het	WORD	
jaar	WORD	
2000	NUMBER	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Hier	WORD	BEGINOFSENTENCE 
is	WORD	
de	WORD	
situatie	WORD	
van	WORD	
de	WORD	
Europese	WORD	
Unie	WORD	
volkomen	WORD	
tegenstrijdig	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Enerzijds	WORD	BEGINOFSENTENCE 
ontstaan	WORD	
door	WORD	
het	WORD	
Verdrag	WORD	
van	WORD	
Amsterdam	WORD	
en	WORD	
de	WORD	
invoering	WORD	
van	WORD	
de	WORD	
euro	WORD	
nieuwe	WORD	
lasten	WORD	NOSPACE 
,	PUNCTUATION	
en	WORD	
anderzijds	WORD	
zijn	WORD	
door	WORD	
de	WORD	
op	WORD	
til	WORD	
zijnde	WORD	
uitbreiding	WORD	
aanvullende	WORD	
financiële	WORD	
inspanningen	WORD	
vereist	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Tenslotte	WORD	BEGINOFSENTENCE 
zetten	WORD	
de	WORD	
zwaardere	WORD	
verantwoordelijkheden	WORD	
van	WORD	
de	WORD	
Unie	WORD	NOSPACE 
,	PUNCTUATION	
en	WORD	
met	WORD	
name	WORD	
de	WORD	
verantwoordelijkheden	WORD	
in	WORD	
Kosovo	WORD	NOSPACE 
,	PUNCTUATION	
de	WORD	
communautaire	WORD	
begroting	WORD	
onder	WORD	
grote	WORD	
spanning	WORD	
en	WORD	
zware	WORD	
druk	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Dat	WORD	BEGINOFSENTENCE 
is	WORD	
de	WORD	
situatie	WORD	
en	WORD	
nu	WORD	
zeggen	WORD	
de	WORD	
instellingen	WORD	
en	WORD	
met	WORD	
name	WORD	
de	WORD	
Raa	WORD	NOSPACE 
.	PUNCTUATION	
waarbij	WORD	
ik	WORD	
mij	WORD	
afvraag	WORD	
wat	WORD	
de	WORD	
Commissie	WORD	
uiteindelijk	WORD	
zal	WORD	
doe	WORD	NOSPACE 
.	PUNCTUATION	
dat	WORD	
zij	WORD	
meer	WORD	
beleidsvormen	WORD	
willen	WORD	
financieren	WORD	NOSPACE 
,	PUNCTUATION	
met	WORD	
meer	WORD	
partners	WORD	NOSPACE 
,	PUNCTUATION	
meer	WORD	
verantwoordelijkheden	WORD	NOSPACE 
,	PUNCTUATION	
maar	WORD	
minder	WORD	
geld	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Dat	WORD	BEGINOFSENTENCE 
is	WORD	NOSPACE 
,	PUNCTUATION	
mijnheer	WORD	
de	WORD	
Voorzitter	WORD	NOSPACE 
,	PUNCTUATION	
de	WORD	
paradox	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Dat	WORD	BEGINOFSENTENCE 
is	WORD	
een	WORD	
voor	WORD	
het	WORD	
Parlement	WORD	
onaanvaardbare	WORD	
tegenstrijdigheid	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

<P>	WORD	BEGINOFSENTENCE 
In	WORD	
dat	WORD	
parket	WORD	
zitten	WORD	
wij	WORD	
nu	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

De	WORD	BEGINOFSENTENCE 
begroting	WORD	
2000	NUMBER	
vertelt	WORD	
enerzijds	WORD	
natuurlijk	WORD	
het	WORD	
verhaal	WORD	
van	WORD	
de	WORD	
zojuist	WORD	
genoemde	WORD	
parado	WORD	NOSPACE 
.	PUNCTUATION	
meer	WORD	
financieren	WORD	
met	WORD	
minder	WORD	
gel	WORD	NOSPACE 
.	PUNCTUATION	
maar	WORD	
zal	WORD	NOSPACE 
,	PUNCTUATION	
naar	WORD	
ik	WORD	
hoop	WORD	NOSPACE 
,	PUNCTUATION	
anderzijds	WORD	
ook	WORD	
duidelijk	WORD	
tot	WORD	
uiting	WORD	
brengen	WORD	
dat	WORD	
het	WORD	
Parlement	WORD	
niet	WORD	
aan	WORD	
deze	WORD	
paradox	WORD	
meedoet	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Hoe	WORD	BEGINOFSENTENCE 
pakken	WORD	
de	WORD	
instellingen	WORD	
nu	WORD	
deze	WORD	
paradox	WORD	
aan	WORD	NOSPACE 
?	PUNCTUATION	ENDOFSENTENCE 

Welnu	WORD	NOSPACE BEGINOFSENTENCE 
,	PUNCTUATION	
heel	WORD	
eenvoudig	WORD	NOSPACE 
,	PUNCTUATION	
met	WORD	
twe	WORD	NOSPACE 
.	PUNCTUATION	
zeer	WORD	
laakbar	WORD	NOSPACE 
.	PUNCTUATION	
methoden	WORD	NOSPACE 
:	PUNCTUATION	
ten	WORD	
eerste	WORD	
vermindering	WORD	
van	WORD	
uitgaven	WORD	
en	WORD	
ten	WORD	
tweede	WORD	
opoffering	WORD	
van	WORD	
traditionele	WORD	
prioriteiten	WORD	
aan	WORD	
nieuwe	WORD	
prioriteiten	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

De	WORD	BEGINOFSENTENCE 
ontwerpbegroting	WORD	
van	WORD	
de	WORD	
Raad	WORD	
is	WORD	
qua	WORD	
opzet	WORD	
voor	WORD	
ons	WORD	
onaanvaardbaar	WORD	
en	WORD	
baart	WORD	
ons	WORD	NOSPACE 
,	PUNCTUATION	
om	WORD	
bovengenoemde	WORD	
redenen	WORD	NOSPACE 
,	PUNCTUATION	
grote	WORD	
zorgen	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Als	WORD	BEGINOFSENTENCE 
ik	WORD	
spreek	WORD	
over	WORD	
uitgavenvermindering	WORD	
denk	WORD	
ik	WORD	
bijvoorbeeld	WORD	
aan	WORD	
de	WORD	
uitgaven	WORD	
van	WORD	
categorie	WORD	
I	WORD	NOSPACE 
,	PUNCTUATION	
waar	WORD	
het	WORD	
voorstel	WORD	
luidt	WORD	NOSPACE 
:	PUNCTUATION	
snoeien	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

De	WORD	BEGINOFSENTENCE 
Commissie	WORD	
was	WORD	
al	WORD	
een	WORD	
verkeerde	WORD	
richting	WORD	
ingeslagen	WORD	
met	WORD	
haar	WORD	
voorontwerp	WORD	
en	WORD	
misschien	WORD	
heeft	WORD	
zij	WORD	
daar	WORD	
nu	WORD	
een	WORD	
beetje	WORD	
spijt	WORD	
van	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Men	WORD	BEGINOFSENTENCE 
stelt	WORD	
ons	WORD	
namelijk	WORD	
lineaire	WORD	
kortingen	WORD	
voor	WORD	
die	WORD	
niet	WORD	
aansluiten	WORD	
bij	WORD	
de	WORD	
realiteit	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Hetzelfde	WORD	BEGINOFSENTENCE 
geldt	WORD	
voor	WORD	
de	WORD	
betalingskredieten	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Voor	WORD	BEGINOFSENTENCE 
de	WORD	
structuurfondsen	WORD	
hebben	WORD	
wij	WORD	
een	WORD	
aanzienlijk	WORD	
volume	WORD	
aan	WORD	
betalingskredieten	WORD	
nodig	WORD	NOSPACE 
,	PUNCTUATION	
zowel	WORD	
ten	WORD	
gevolge	WORD	
van	WORD	
de	WORD	
uitvoering	WORD	
van	WORD	
de	WORD	
nieuwe	WORD	
maatregelen	WORD	
van	WORD	
Agenda	WORD	
2000	NUMBER	NOSPACE 
,	PUNCTUATION	
als	WORD	
ten	WORD	
gevolge	WORD	
van	WORD	
de	WORD	
last	WORD	
uit	WORD	
het	WORD	
verleden	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Deze	WORD	BEGINOFSENTENCE 
last	WORD	
uit	WORD	
het	WORD	
verleden	WORD	
komt	WORD	
bij	WORD	
mij	WORD	
over	WORD	
als	WORD	
het	WORD	
gerochel	WORD	
van	WORD	
een	WORD	
stervende	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Het	WORD	BEGINOFSENTENCE 
gaat	WORD	
hierbij	WORD	
namelijk	WORD	
om	WORD	
nog	WORD	
uitstaande	WORD	
betalingen	WORD	
op	WORD	
grond	WORD	
van	WORD	
reeds	WORD	
verstreken	WORD	
programma	WORD	NOSPACE 
'	PUNCTUATION	
s	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

<P>	WORD	BEGINOFSENTENCE 
Daardoor	WORD	
moeten	WORD	
aanzienlijke	WORD	
betalingsinspanningen	WORD	
worden	WORD	
ondernomen	WORD	
en	WORD	
ten	WORD	
aanzien	WORD	
daarvan	WORD	
doet	WORD	
de	WORD	
Raad	WORD	
niet	WORD	
met	WORD	
ons	WORD	
en	WORD	
niet	WORD	
met	WORD	
de	WORD	
Commissie	WORD	
mee	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Integendeel	WORD	NOSPACE BEGINOFSENTENCE 
,	PUNCTUATION	
hij	WORD	
stelt	WORD	
juist	WORD	
een	WORD	
volledig	WORD	
ontoelaatbare	WORD	
vermindering	WORD	
voor	WORD	
ten	WORD	
opzichte	WORD	
van	WORD	
het	WORD	
VOB	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

<P>	WORD	BEGINOFSENTENCE 
De	WORD	
Commissie	WORD	
had	WORD	
de	WORD	
afgelopen	WORD	
maanden	WORD	
een	WORD	
nogal	WORD	
aarzelende	WORD	
houding	WORD	
ten	WORD	
aanzien	WORD	
van	WORD	
deze	WORD	
kwestie	WORD	NOSPACE 
,	PUNCTUATION	
maar	WORD	
lijkt	WORD	
nu	WORD	
tot	WORD	
andere	WORD	NOSPACE 
,	PUNCTUATION	
betere	WORD	
gedachten	WORD	
te	WORD	
zijn	WORD	
gekomen	WORD	NOSPACE 
,	PUNCTUATION	
en	WORD	
daar	WORD	
zijn	WORD	
wij	WORD	
blij	WORD	
om	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

We	WORD	BEGINOFSENTENCE 
hebben	WORD	
hier	WORD	
dus	WORD	
een	WORD	
vermindering	WORD	
van	WORD	
de	WORD	
uitgaven	WORD	
en	WORD	
de	WORD	
kredieten	WORD	
voor	WORD	
reeds	WORD	
bestaande	WORD	
en	WORD	
voor	WORD	
toekomstige	WORD	
behoeften	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Hetzelfde	WORD	BEGINOFSENTENCE 
geldt	WORD	
voor	WORD	
de	WORD	
uitgaven	WORD	
van	WORD	
categorie	WORD	
V.	INITIAL	
<P>	WORD	
Tegelijkertijd	WORD	
worde	WORD	NOSPACE 
.	PUNCTUATION	
en	WORD	
dat	WORD	
is	WORD	
ontoelaatbaa	WORD	NOSPACE 
.	PUNCTUATION	
de	WORD	
prioriteiten	WORD	
van	WORD	
gisteren	WORD	
en	WORD	
vandaag	WORD	
opgeofferd	WORD	
aan	WORD	
de	WORD	
prioriteiten	WORD	
van	WORD	
morgen	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Ik	WORD	BEGINOFSENTENCE 
vind	WORD	
dat	WORD	
een	WORD	
zeer	WORD	
ernstige	WORD	
zaak	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

In	WORD	BEGINOFSENTENCE 
categorie	WORD	
IV	WORD	
stelt	WORD	
de	WORD	
Commissie	WORD	
ons	WORD	
een	WORD	
lineaire	WORD	
korting	WORD	
voor	WORD	NOSPACE 
,	PUNCTUATION	
zonder	WORD	
opgaaf	WORD	
van	WORD	
redenen	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Dit	WORD	BEGINOFSENTENCE 
voorstel	WORD	
is	WORD	
voor	WORD	
ons	WORD	
absoluut	WORD	
onaanvaardbaar	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Ik	WORD	BEGINOFSENTENCE 
zeg	WORD	
dit	WORD	
met	WORD	
nadruk	WORD	NOSPACE 
:	PUNCTUATION	
wij	WORD	
hebben	WORD	
het	WORD	
volste	WORD	
begrip	WORD	
voor	WORD	
kortingen	WORD	NOSPACE 
,	PUNCTUATION	
mits	WORD	
zij	WORD	
gerechtvaardigd	WORD	
zijn	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Zo	WORD	BEGINOFSENTENCE 
gaat	WORD	
dit	WORD	
echter	WORD	
niet	WORD	NOSPACE 
!	PUNCTUATION	ENDOFSENTENCE 

Men	WORD	BEGINOFSENTENCE 
zegt	WORD	
ons	WORD	
dat	WORD	
er	WORD	
geld	WORD	
moet	WORD	
komen	WORD	
voor	WORD	
Kosovo	WORD	NOSPACE 
,	PUNCTUATION	
Marokko	WORD	NOSPACE 
,	PUNCTUATION	
Timor	WORD	
en	WORD	
Turkije	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Timor	WORD	BEGINOFSENTENCE 
en	WORD	
Turkije	WORD	
staan	WORD	
nog	WORD	
niet	WORD	
op	WORD	
de	WORD	
ontwerpbegroting	WORD	NOSPACE 
,	PUNCTUATION	
maar	WORD	
dat	WORD	
komt	WORD	
nog	WORD	
wel	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Men	WORD	BEGINOFSENTENCE 
zegt	WORD	
ons	WORD	
dat	WORD	
dit	WORD	
alles	WORD	
gefinancierd	WORD	
moet	WORD	
worden	WORD	
en	WORD	
daarom	WORD	
het	WORD	
mes	WORD	
gezet	WORD	
moet	WORD	
worden	WORD	
in	WORD	
alle	WORD	
traditionele	WORD	
ontwikkelingskredieten	WORD	
voor	WORD	
hulp	WORD	
aan	WORD	
Afrika	WORD	NOSPACE 
,	PUNCTUATION	
Azië	WORD	
en	WORD	
Latijns-Amerika	WORD-COMPOUND	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Het	WORD	
Parlement	WORD	
zegt	WORD	
echter	WORD	NOSPACE 
:	PUNCTUATION	
"	PUNCTUATION	NOSPACE ENDQUOTE 
Geen	WORD	
sprake	WORD	
van	WORD	NOSPACE 
,	PUNCTUATION	
wij	WORD	
aanvaarden	WORD	
niet	WORD	
dat	WORD	
Kosovo	WORD	
wordt	WORD	
betaald	WORD	
door	WORD	
Afrika	WORD	NOSPACE 
,	PUNCTUATION	
Latijns-Amerika	WORD-COMPOUND	
en	WORD	
Azië	WORD	NOSPACE 
,	PUNCTUATION	
dat	WORD	
wil	WORD	
zeggen	WORD	
door	WORD	
iedereen	WORD	NOSPACE 
,	PUNCTUATION	
behalve	WORD	
Europa	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Zo	WORD	BEGINOFSENTENCE 
gaat	WORD	
dat	WORD	
niet	WORD	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 


