Met	WORD	BEGINOFSENTENCE NEWPARAGRAPH 
www.google.com	URL-WWW	
is	WORD	
mijn	WORD	
homepage	WORD	
is	WORD	
te	WORD	
vinden	WORD	
op	WORD	
http://proycon.anaproy.nl	URL	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Per	WORD	BEGINOFSENTENCE 
e-mail	WORD-COMPOUND	
ben	WORD	
ik	WORD	
te	WORD	
bereiken	WORD	
op	WORD	
proycon@anaproy.nl	E-MAIL	
of	WORD	
m.van.gompel@uvt.nl	E-MAIL	NOSPACE 
.	PUNCTUATION	ENDOFSENTENCE 

Mijn	WORD	BEGINOFSENTENCE 
domein	WORD	
is	WORD	
anaproy.nl	URL-DOMAIN	NOSPACE 
,	PUNCTUATION	
en	WORD	
kijk	WORD	
ook	WORD	
eens	WORD	
even	WORD	
op	WORD	
valkuil.net	URL-DOMAIN	NOSPACE 
!	PUNCTUATION	ENDOFSENTENCE 

De	WORD	BEGINOFSENTENCE NEWPARAGRAPH 
URL	WORD	
http://www.consument-en-veiligheid.nl	URL	
is	WORD	
tricky	WORD	NOSPACE 
!	PUNCTUATION	ENDOFSENTENCE 

Deze	WORD	BEGINOFSENTENCE NEWPARAGRAPH 
beide	WORD	
ook	WORD	NOSPACE 
:	PUNCTUATION	
http://ue.eu.int/Pesc/default.asp?lang=nl	URL	
http://www.deverdiepingvannederland.nl/	URL	ENDOFSENTENCE 

En	WORD	BEGINOFSENTENCE NEWPARAGRAPH 
dit	WORD	NOSPACE 
:	PUNCTUATION	
www.deverdiepingvannederland.nl/index.html	URL-WWW	
versus	WORD	NOSPACE 
:	PUNCTUATION	
www.deverdiepingvannederland.nl/	URL-WWW	ENDOFSENTENCE 


